// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.17.3
// source: pkg/mcclient/mcuser/mcuser_proto.proto

package mcuser

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type McUserProto_UserStatus int32

const (
	McUserProto_UNSET              McUserProto_UserStatus = 0
	McUserProto_OK                 McUserProto_UserStatus = 1
	McUserProto_ERROR_GENERIC      McUserProto_UserStatus = 2
	McUserProto_ERROR_UNKNOWN_USER McUserProto_UserStatus = 3
	McUserProto_ERROR_RATE_LIMIT   McUserProto_UserStatus = 4
)

// Enum value maps for McUserProto_UserStatus.
var (
	McUserProto_UserStatus_name = map[int32]string{
		0: "UNSET",
		1: "OK",
		2: "ERROR_GENERIC",
		3: "ERROR_UNKNOWN_USER",
		4: "ERROR_RATE_LIMIT",
	}
	McUserProto_UserStatus_value = map[string]int32{
		"UNSET":              0,
		"OK":                 1,
		"ERROR_GENERIC":      2,
		"ERROR_UNKNOWN_USER": 3,
		"ERROR_RATE_LIMIT":   4,
	}
)

func (x McUserProto_UserStatus) Enum() *McUserProto_UserStatus {
	p := new(McUserProto_UserStatus)
	*p = x
	return p
}

func (x McUserProto_UserStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (McUserProto_UserStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_mcclient_mcuser_mcuser_proto_proto_enumTypes[0].Descriptor()
}

func (McUserProto_UserStatus) Type() protoreflect.EnumType {
	return &file_pkg_mcclient_mcuser_mcuser_proto_proto_enumTypes[0]
}

func (x McUserProto_UserStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use McUserProto_UserStatus.Descriptor instead.
func (McUserProto_UserStatus) EnumDescriptor() ([]byte, []int) {
	return file_pkg_mcclient_mcuser_mcuser_proto_proto_rawDescGZIP(), []int{0, 0}
}

// Supports other value incase another Texture host is ever used
type McUserProto_URLType int32

const (
	McUserProto_UNKNOWN         McUserProto_URLType = 0
	McUserProto_TEXTURES_MC_NET McUserProto_URLType = 1
)

// Enum value maps for McUserProto_URLType.
var (
	McUserProto_URLType_name = map[int32]string{
		0: "UNKNOWN",
		1: "TEXTURES_MC_NET",
	}
	McUserProto_URLType_value = map[string]int32{
		"UNKNOWN":         0,
		"TEXTURES_MC_NET": 1,
	}
)

func (x McUserProto_URLType) Enum() *McUserProto_URLType {
	p := new(McUserProto_URLType)
	*p = x
	return p
}

func (x McUserProto_URLType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (McUserProto_URLType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_mcclient_mcuser_mcuser_proto_proto_enumTypes[1].Descriptor()
}

func (McUserProto_URLType) Type() protoreflect.EnumType {
	return &file_pkg_mcclient_mcuser_mcuser_proto_proto_enumTypes[1]
}

func (x McUserProto_URLType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use McUserProto_URLType.Descriptor instead.
func (McUserProto_URLType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_mcclient_mcuser_mcuser_proto_proto_rawDescGZIP(), []int{0, 1}
}

type McUserProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time     uint32                 `protobuf:"varint,1,opt,name=Time,proto3" json:"Time,omitempty"`
	Status   McUserProto_UserStatus `protobuf:"varint,2,opt,name=Status,proto3,enum=mcuser.McUserProto_UserStatus" json:"Status,omitempty"`
	Username string                 `protobuf:"bytes,4,opt,name=Username,proto3" json:"Username,omitempty"`
	UUID     string                 `protobuf:"bytes,5,opt,name=UUID,proto3" json:"UUID,omitempty"`
	BaseURL  McUserProto_URLType    `protobuf:"varint,7,opt,name=BaseURL,proto3,enum=mcuser.McUserProto_URLType" json:"BaseURL,omitempty"`
	//bool SkinSlim = 8
	SkinPath string `protobuf:"bytes,9,opt,name=SkinPath,proto3" json:"SkinPath,omitempty"` //string CapePath = 10;
}

func (x *McUserProto) Reset() {
	*x = McUserProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_mcclient_mcuser_mcuser_proto_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *McUserProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*McUserProto) ProtoMessage() {}

func (x *McUserProto) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_mcclient_mcuser_mcuser_proto_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use McUserProto.ProtoReflect.Descriptor instead.
func (*McUserProto) Descriptor() ([]byte, []int) {
	return file_pkg_mcclient_mcuser_mcuser_proto_proto_rawDescGZIP(), []int{0}
}

func (x *McUserProto) GetTime() uint32 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *McUserProto) GetStatus() McUserProto_UserStatus {
	if x != nil {
		return x.Status
	}
	return McUserProto_UNSET
}

func (x *McUserProto) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *McUserProto) GetUUID() string {
	if x != nil {
		return x.UUID
	}
	return ""
}

func (x *McUserProto) GetBaseURL() McUserProto_URLType {
	if x != nil {
		return x.BaseURL
	}
	return McUserProto_UNKNOWN
}

func (x *McUserProto) GetSkinPath() string {
	if x != nil {
		return x.SkinPath
	}
	return ""
}

var File_pkg_mcclient_mcuser_mcuser_proto_proto protoreflect.FileDescriptor

var file_pkg_mcclient_mcuser_mcuser_proto_proto_rawDesc = []byte{
	0x0a, 0x26, 0x70, 0x6b, 0x67, 0x2f, 0x6d, 0x63, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x6d,
	0x63, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x6d, 0x63, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6d, 0x63, 0x75, 0x73, 0x65, 0x72,
	0x22, 0xeb, 0x02, 0x0a, 0x0b, 0x4d, 0x63, 0x55, 0x73, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x12, 0x0a, 0x04, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04,
	0x54, 0x69, 0x6d, 0x65, 0x12, 0x36, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x6d, 0x63, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x4d, 0x63,
	0x55, 0x73, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1a, 0x0a, 0x08,
	0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x55, 0x55, 0x49, 0x44,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x55, 0x55, 0x49, 0x44, 0x12, 0x35, 0x0a, 0x07,
	0x42, 0x61, 0x73, 0x65, 0x55, 0x52, 0x4c, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e,
	0x6d, 0x63, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x4d, 0x63, 0x55, 0x73, 0x65, 0x72, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x55, 0x52, 0x4c, 0x54, 0x79, 0x70, 0x65, 0x52, 0x07, 0x42, 0x61, 0x73, 0x65,
	0x55, 0x52, 0x4c, 0x12, 0x1a, 0x0a, 0x08, 0x53, 0x6b, 0x69, 0x6e, 0x50, 0x61, 0x74, 0x68, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x53, 0x6b, 0x69, 0x6e, 0x50, 0x61, 0x74, 0x68, 0x22,
	0x60, 0x0a, 0x0a, 0x55, 0x73, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x09, 0x0a,
	0x05, 0x55, 0x4e, 0x53, 0x45, 0x54, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x01,
	0x12, 0x11, 0x0a, 0x0d, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x5f, 0x47, 0x45, 0x4e, 0x45, 0x52, 0x49,
	0x43, 0x10, 0x02, 0x12, 0x16, 0x0a, 0x12, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x5f, 0x55, 0x4e, 0x4b,
	0x4e, 0x4f, 0x57, 0x4e, 0x5f, 0x55, 0x53, 0x45, 0x52, 0x10, 0x03, 0x12, 0x14, 0x0a, 0x10, 0x45,
	0x52, 0x52, 0x4f, 0x52, 0x5f, 0x52, 0x41, 0x54, 0x45, 0x5f, 0x4c, 0x49, 0x4d, 0x49, 0x54, 0x10,
	0x04, 0x22, 0x2b, 0x0a, 0x07, 0x55, 0x52, 0x4c, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07,
	0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f, 0x54, 0x45, 0x58,
	0x54, 0x55, 0x52, 0x45, 0x53, 0x5f, 0x4d, 0x43, 0x5f, 0x4e, 0x45, 0x54, 0x10, 0x01, 0x42, 0x2d,
	0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x69, 0x6e,
	0x6f, 0x74, 0x61, 0x72, 0x2f, 0x69, 0x6d, 0x67, 0x64, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x6d, 0x63,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x6d, 0x63, 0x75, 0x73, 0x65, 0x72, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_mcclient_mcuser_mcuser_proto_proto_rawDescOnce sync.Once
	file_pkg_mcclient_mcuser_mcuser_proto_proto_rawDescData = file_pkg_mcclient_mcuser_mcuser_proto_proto_rawDesc
)

func file_pkg_mcclient_mcuser_mcuser_proto_proto_rawDescGZIP() []byte {
	file_pkg_mcclient_mcuser_mcuser_proto_proto_rawDescOnce.Do(func() {
		file_pkg_mcclient_mcuser_mcuser_proto_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_mcclient_mcuser_mcuser_proto_proto_rawDescData)
	})
	return file_pkg_mcclient_mcuser_mcuser_proto_proto_rawDescData
}

var file_pkg_mcclient_mcuser_mcuser_proto_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pkg_mcclient_mcuser_mcuser_proto_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pkg_mcclient_mcuser_mcuser_proto_proto_goTypes = []interface{}{
	(McUserProto_UserStatus)(0), // 0: mcuser.McUserProto.UserStatus
	(McUserProto_URLType)(0),    // 1: mcuser.McUserProto.URLType
	(*McUserProto)(nil),         // 2: mcuser.McUserProto
}
var file_pkg_mcclient_mcuser_mcuser_proto_proto_depIdxs = []int32{
	0, // 0: mcuser.McUserProto.Status:type_name -> mcuser.McUserProto.UserStatus
	1, // 1: mcuser.McUserProto.BaseURL:type_name -> mcuser.McUserProto.URLType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_mcclient_mcuser_mcuser_proto_proto_init() }
func file_pkg_mcclient_mcuser_mcuser_proto_proto_init() {
	if File_pkg_mcclient_mcuser_mcuser_proto_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_mcclient_mcuser_mcuser_proto_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*McUserProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_mcclient_mcuser_mcuser_proto_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_mcclient_mcuser_mcuser_proto_proto_goTypes,
		DependencyIndexes: file_pkg_mcclient_mcuser_mcuser_proto_proto_depIdxs,
		EnumInfos:         file_pkg_mcclient_mcuser_mcuser_proto_proto_enumTypes,
		MessageInfos:      file_pkg_mcclient_mcuser_mcuser_proto_proto_msgTypes,
	}.Build()
	File_pkg_mcclient_mcuser_mcuser_proto_proto = out.File
	file_pkg_mcclient_mcuser_mcuser_proto_proto_rawDesc = nil
	file_pkg_mcclient_mcuser_mcuser_proto_proto_goTypes = nil
	file_pkg_mcclient_mcuser_mcuser_proto_proto_depIdxs = nil
}
