// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.17.3
// source: pkg/mcclient/mcuser_proto/mcuser.proto

package mcuser_proto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type McUserProto_URLType int32

const (
	McUserProto_UNKNOWN         McUserProto_URLType = 0
	McUserProto_TEXTURES_MC_NET McUserProto_URLType = 1
)

// Enum value maps for McUserProto_URLType.
var (
	McUserProto_URLType_name = map[int32]string{
		0: "UNKNOWN",
		1: "TEXTURES_MC_NET",
	}
	McUserProto_URLType_value = map[string]int32{
		"UNKNOWN":         0,
		"TEXTURES_MC_NET": 1,
	}
)

func (x McUserProto_URLType) Enum() *McUserProto_URLType {
	p := new(McUserProto_URLType)
	*p = x
	return p
}

func (x McUserProto_URLType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (McUserProto_URLType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_mcclient_mcuser_proto_mcuser_proto_enumTypes[0].Descriptor()
}

func (McUserProto_URLType) Type() protoreflect.EnumType {
	return &file_pkg_mcclient_mcuser_proto_mcuser_proto_enumTypes[0]
}

func (x McUserProto_URLType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use McUserProto_URLType.Descriptor instead.
func (McUserProto_URLType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_mcclient_mcuser_proto_mcuser_proto_rawDescGZIP(), []int{0, 0}
}

type McUserProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time     uint32              `protobuf:"varint,1,opt,name=Time,proto3" json:"Time,omitempty"`
	Username string              `protobuf:"bytes,3,opt,name=Username,proto3" json:"Username,omitempty"`
	UUID     string              `protobuf:"bytes,4,opt,name=UUID,proto3" json:"UUID,omitempty"`
	BaseURL  McUserProto_URLType `protobuf:"varint,6,opt,name=BaseURL,proto3,enum=mcuser_proto.McUserProto_URLType" json:"BaseURL,omitempty"`
	SkinURL  string              `protobuf:"bytes,7,opt,name=SkinURL,proto3" json:"SkinURL,omitempty"` //string CapePath = 8;
}

func (x *McUserProto) Reset() {
	*x = McUserProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_mcclient_mcuser_proto_mcuser_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *McUserProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*McUserProto) ProtoMessage() {}

func (x *McUserProto) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_mcclient_mcuser_proto_mcuser_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use McUserProto.ProtoReflect.Descriptor instead.
func (*McUserProto) Descriptor() ([]byte, []int) {
	return file_pkg_mcclient_mcuser_proto_mcuser_proto_rawDescGZIP(), []int{0}
}

func (x *McUserProto) GetTime() uint32 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *McUserProto) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *McUserProto) GetUUID() string {
	if x != nil {
		return x.UUID
	}
	return ""
}

func (x *McUserProto) GetBaseURL() McUserProto_URLType {
	if x != nil {
		return x.BaseURL
	}
	return McUserProto_UNKNOWN
}

func (x *McUserProto) GetSkinURL() string {
	if x != nil {
		return x.SkinURL
	}
	return ""
}

var File_pkg_mcclient_mcuser_proto_mcuser_proto protoreflect.FileDescriptor

var file_pkg_mcclient_mcuser_proto_mcuser_proto_rawDesc = []byte{
	0x0a, 0x26, 0x70, 0x6b, 0x67, 0x2f, 0x6d, 0x63, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x6d,
	0x63, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x63, 0x75, 0x73,
	0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x6d, 0x63, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd5, 0x01, 0x0a, 0x0b, 0x4d, 0x63, 0x55, 0x73, 0x65,
	0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x73,
	0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x55, 0x73,
	0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x55, 0x55, 0x49, 0x44, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x55, 0x55, 0x49, 0x44, 0x12, 0x3b, 0x0a, 0x07, 0x42, 0x61,
	0x73, 0x65, 0x55, 0x52, 0x4c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x21, 0x2e, 0x6d, 0x63,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x63, 0x55, 0x73, 0x65,
	0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x52, 0x4c, 0x54, 0x79, 0x70, 0x65, 0x52, 0x07,
	0x42, 0x61, 0x73, 0x65, 0x55, 0x52, 0x4c, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x6b, 0x69, 0x6e, 0x55,
	0x52, 0x4c, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x53, 0x6b, 0x69, 0x6e, 0x55, 0x52,
	0x4c, 0x22, 0x2b, 0x0a, 0x07, 0x55, 0x52, 0x4c, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07,
	0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f, 0x54, 0x45, 0x58,
	0x54, 0x55, 0x52, 0x45, 0x53, 0x5f, 0x4d, 0x43, 0x5f, 0x4e, 0x45, 0x54, 0x10, 0x01, 0x42, 0x33,
	0x5a, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x69, 0x6e,
	0x6f, 0x74, 0x61, 0x72, 0x2f, 0x69, 0x6d, 0x67, 0x64, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x6d, 0x63,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x6d, 0x63, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_mcclient_mcuser_proto_mcuser_proto_rawDescOnce sync.Once
	file_pkg_mcclient_mcuser_proto_mcuser_proto_rawDescData = file_pkg_mcclient_mcuser_proto_mcuser_proto_rawDesc
)

func file_pkg_mcclient_mcuser_proto_mcuser_proto_rawDescGZIP() []byte {
	file_pkg_mcclient_mcuser_proto_mcuser_proto_rawDescOnce.Do(func() {
		file_pkg_mcclient_mcuser_proto_mcuser_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_mcclient_mcuser_proto_mcuser_proto_rawDescData)
	})
	return file_pkg_mcclient_mcuser_proto_mcuser_proto_rawDescData
}

var file_pkg_mcclient_mcuser_proto_mcuser_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_mcclient_mcuser_proto_mcuser_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pkg_mcclient_mcuser_proto_mcuser_proto_goTypes = []interface{}{
	(McUserProto_URLType)(0), // 0: mcuser_proto.McUserProto.URLType
	(*McUserProto)(nil),      // 1: mcuser_proto.McUserProto
}
var file_pkg_mcclient_mcuser_proto_mcuser_proto_depIdxs = []int32{
	0, // 0: mcuser_proto.McUserProto.BaseURL:type_name -> mcuser_proto.McUserProto.URLType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_mcclient_mcuser_proto_mcuser_proto_init() }
func file_pkg_mcclient_mcuser_proto_mcuser_proto_init() {
	if File_pkg_mcclient_mcuser_proto_mcuser_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_mcclient_mcuser_proto_mcuser_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*McUserProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_mcclient_mcuser_proto_mcuser_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_mcclient_mcuser_proto_mcuser_proto_goTypes,
		DependencyIndexes: file_pkg_mcclient_mcuser_proto_mcuser_proto_depIdxs,
		EnumInfos:         file_pkg_mcclient_mcuser_proto_mcuser_proto_enumTypes,
		MessageInfos:      file_pkg_mcclient_mcuser_proto_mcuser_proto_msgTypes,
	}.Build()
	File_pkg_mcclient_mcuser_proto_mcuser_proto = out.File
	file_pkg_mcclient_mcuser_proto_mcuser_proto_rawDesc = nil
	file_pkg_mcclient_mcuser_proto_mcuser_proto_goTypes = nil
	file_pkg_mcclient_mcuser_proto_mcuser_proto_depIdxs = nil
}
