// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.17.3
// source: pkg/mcclient/mcuser_proto/mcuser.proto

package mcuser_proto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type McUserProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time     uint32 `protobuf:"varint,1,opt,name=Time,proto3" json:"Time,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=Username,proto3" json:"Username,omitempty"`
	UUID     string `protobuf:"bytes,3,opt,name=UUID,proto3" json:"UUID,omitempty"`
	SkinPath string `protobuf:"bytes,4,opt,name=SkinPath,proto3" json:"SkinPath,omitempty"` //string CapePath = 5;
}

func (x *McUserProto) Reset() {
	*x = McUserProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_mcclient_mcuser_proto_mcuser_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *McUserProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*McUserProto) ProtoMessage() {}

func (x *McUserProto) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_mcclient_mcuser_proto_mcuser_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use McUserProto.ProtoReflect.Descriptor instead.
func (*McUserProto) Descriptor() ([]byte, []int) {
	return file_pkg_mcclient_mcuser_proto_mcuser_proto_rawDescGZIP(), []int{0}
}

func (x *McUserProto) GetTime() uint32 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *McUserProto) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *McUserProto) GetUUID() string {
	if x != nil {
		return x.UUID
	}
	return ""
}

func (x *McUserProto) GetSkinPath() string {
	if x != nil {
		return x.SkinPath
	}
	return ""
}

var File_pkg_mcclient_mcuser_proto_mcuser_proto protoreflect.FileDescriptor

var file_pkg_mcclient_mcuser_proto_mcuser_proto_rawDesc = []byte{
	0x0a, 0x26, 0x70, 0x6b, 0x67, 0x2f, 0x6d, 0x63, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x6d,
	0x63, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x63, 0x75, 0x73,
	0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x6d, 0x63, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6d, 0x0a, 0x0b, 0x4d, 0x63, 0x55, 0x73, 0x65, 0x72,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x04, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x73, 0x65,
	0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x55, 0x73, 0x65,
	0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x55, 0x55, 0x49, 0x44, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x55, 0x55, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x53, 0x6b, 0x69,
	0x6e, 0x50, 0x61, 0x74, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x53, 0x6b, 0x69,
	0x6e, 0x50, 0x61, 0x74, 0x68, 0x42, 0x33, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x69, 0x6e, 0x6f, 0x74, 0x61, 0x72, 0x2f, 0x69, 0x6d, 0x67, 0x64,
	0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x6d, 0x63, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x6d, 0x63,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_pkg_mcclient_mcuser_proto_mcuser_proto_rawDescOnce sync.Once
	file_pkg_mcclient_mcuser_proto_mcuser_proto_rawDescData = file_pkg_mcclient_mcuser_proto_mcuser_proto_rawDesc
)

func file_pkg_mcclient_mcuser_proto_mcuser_proto_rawDescGZIP() []byte {
	file_pkg_mcclient_mcuser_proto_mcuser_proto_rawDescOnce.Do(func() {
		file_pkg_mcclient_mcuser_proto_mcuser_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_mcclient_mcuser_proto_mcuser_proto_rawDescData)
	})
	return file_pkg_mcclient_mcuser_proto_mcuser_proto_rawDescData
}

var file_pkg_mcclient_mcuser_proto_mcuser_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pkg_mcclient_mcuser_proto_mcuser_proto_goTypes = []interface{}{
	(*McUserProto)(nil), // 0: mcuser_proto.McUserProto
}
var file_pkg_mcclient_mcuser_proto_mcuser_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_mcclient_mcuser_proto_mcuser_proto_init() }
func file_pkg_mcclient_mcuser_proto_mcuser_proto_init() {
	if File_pkg_mcclient_mcuser_proto_mcuser_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_mcclient_mcuser_proto_mcuser_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*McUserProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_mcclient_mcuser_proto_mcuser_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_mcclient_mcuser_proto_mcuser_proto_goTypes,
		DependencyIndexes: file_pkg_mcclient_mcuser_proto_mcuser_proto_depIdxs,
		MessageInfos:      file_pkg_mcclient_mcuser_proto_mcuser_proto_msgTypes,
	}.Build()
	File_pkg_mcclient_mcuser_proto_mcuser_proto = out.File
	file_pkg_mcclient_mcuser_proto_mcuser_proto_rawDesc = nil
	file_pkg_mcclient_mcuser_proto_mcuser_proto_goTypes = nil
	file_pkg_mcclient_mcuser_proto_mcuser_proto_depIdxs = nil
}
