<!DOCTYPE html>
<html lang="en">
    <?php require "template/head.phtml"; ?> 
    <body>
        <div class="container">
            <div class="row-fluid">
                <div class="span9 content">
                    <h1>404</h1>
                    <p class="center">The requested content cannot be found</p>
                    <p class="center"><a href="<?php echo URL; ?>">&larr; Return to Minotar</a></p>
                </div>
            </div>
        </div>
    </body>
</html>
