<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Minotar - 404</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <!-- Style -->
        <link href="../style.css" rel="stylesheet">
        <style type="text/css">
            h1 {
                font-family: 'Cabin Sketch', cursive;
                font-size: 150px;
                text-align: center;

                margin-top: 63px;
                padding-bottom: 60px;
            }
            h1 a,a:hover {
                text-decoration: none;
                color: #000;
            }
            .center {
                text-align: center;
            }
        </style>

        <!--[if lt IE 9]>
                <script src="https://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->

        <script type="text/javascript">

            var _gaq = _gaq || [];
            _gaq.push(['_setAccount', 'UA-22574465-1']);
            _gaq.push(['_trackPageview']);

            (function() {
                var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
                ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
                var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
            })();

        </script>
    </head>

    <body>
        <div class="container">
            <div class="row-fluid">
                <div class="span9 content">
                    <h1>404</h1>
                    <p class="center">The requested content cannot be found</p>
                    <p class="center"><a href="http://minotar.net/">&larr; Return to minotar.net</a></p>
                </div>
            </div>
        </div>
    </body>
</html>
