<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>Minotar - The Miner's Avatar</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta name="description" content="A Minotar is a global avatar that pulls your head off of your Minecraft.net skin, and allows it for use on thousands of sites. See some uses below.">
		<meta name="author" content="Axxim, LLC">

		<!-- Le styles -->
		<link href="./style.css" rel="stylesheet">
		<style type="text/css">
		h1 {
			font-family: 'Cabin Sketch', cursive;
			font-size: 150px;
			text-align: center;

			margin-top: 63px;
			padding-bottom: 60px;
		}
		h1 a,a:hover {
			text-decoration: none;
			color: #000;
		}
		.center {
			text-align: center;
		}
		.green {
			color: #00FF00;
		}
		.red {
			color: #DC143C;
		}
		.blue {
			color: #1E90FF;
		}
		</style>

		<!--[if lt IE 9]>
			<script src="https://html5shim.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->

		<link rel="shortcut icon" href="https://minotar.net/avatar/clone1018/128.png">

		<script type="text/javascript">

			var _gaq = _gaq || [];
			_gaq.push(['_setAccount', 'UA-22574465-1']);
			_gaq.push(['_trackPageview']);

			(function() {
				var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
				ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
				var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
			})();

		</script>
	</head>

	<body>
		<a href="https://github.com/axxim/minotar"><img style="position: absolute; top: 0; left: 0; border: 0;" src="https://s3.amazonaws.com/github/ribbons/forkme_left_darkblue_121621.png" alt="Fork me on GitHub"></a>
		<div class="container">
			<div class="row-fluid">
				<div class="span9 content">
					<h1><a href="/">Minotar</a></h1>

					<p>A Minotar is a global avatar that pulls your head off of your Minecraft.net skin, and allows it for use on thousands of sites. See some uses below.</p>

					<p class="center hidden-phone">
						<img src="https://minotar.net/avatar/clone1018/64" alt="clone1018"> 
						<img src="https://minotar.net/avatar/citricsquid/64" alt="citricsquid"> 
						<img src="https://minotar.net/avatar/Raitsui/64" alt="Raitsui"> 
						<img src="https://minotar.net/avatar/runforthefinish/64" alt="runforthefinish"> 
						<img src="https://minotar.net/avatar/NoMercyJon/64" alt="NoMercyJon"> 
						<img src="https://minotar.net/avatar/Nautika/64" alt="Nautika"> 
						<img src="https://minotar.net/avatar/Notch/64" alt="Notch"> 
						<img src="https://minotar.net/helm/NiteAngel/64" alt="NiteAngel">
						<img src="https://minotar.net/helm/S1NZ/64" alt="S1NZ"> 
						<img src="https://minotar.net/helm/drupal/64" alt="drupal">
						<img src="https://minotar.net/helm/KakashiSuno/64" alt="KakashiSuno">
					</p>

					<h2>Sweet and Simple API</h2><br>

					<h4>Simple Heads</h4>
					<p>Unlike the PayPal API, we keep things nice and simple. For basic usage just provide a username:</p>
					<pre>&#60;img src="https://minotar.net/avatar/<span class="blue">clone1018</span>"&#62;</pre>
					
					<p>You can also set a size. We use pixels and we only need the <span class="red">width</span>. Just add it to the end.</p>
					<pre>&#60;img src="https://minotar.net/avatar/<span class="blue">clone1018</span>/<span class="red">100</span>"&#62;</pre>
					
					<p>And because some services require an extension, we've added simple support for it. Just add <span class="green">.png</span> to the end.</p>
					<pre>&#60;img src="https://minotar.net/avatar/<span class="blue">clone1018</span>/<span class="red">100</span><span class="green">.png</span>"&#62;</pre><br>

					<h4>Avatar With Helm</h4>
					<p>Sometimes you want to display a helm too, that's fine with this endpoint:</p>
					<pre>&#60;img src="https://minotar.net/helm/<span class="blue">clone1018</span>/<span class="red">100</span><span class="green">.png</span>"&#62;</pre><br>

					<h4>User's Skin</h4>
					<p>You can even use Minotar's API to get a users skin. <em>We're adding more soon!</em></p>
					<pre>&#60;img src="https://minotar.net/skin/<span class="blue">clone1018</span>"&#62;</pre>

					<p>You can also set the browser to download the image by using:</p>
					<pre>https://minotar.net/download/<span class="blue">clone1018</span></pre><br>

					<h4>Random Skin</h4>
					<p>Randomly generated head? We got that too.</p>
					<pre>&#60;img src="https://minotar.net/random/<span class="red">100</span><span class="green">.png</span>"&#62;</pre>
					<br>

					<p><a href="http://axxim.net">Copyright 2012 - Axxim, LLC</a></p>
					<p>Bandwidth Provided by <a href="http://vpsno.de">VPSNode</a></p>

				</div>
				<div class="span3 hidden-phone center" id="right">

					<img src="https://minotar.net/avatar/clone1018/250.png">

					<h2>Requests</h2>
					<h3 id="pageviews"><?php echo file_get_contents('count'); ?></h3><br>
					<!-- this is NOT real time, but emulated, base number is updated often -->

					<h2>Who Uses Minotar?</h2><br>

					<p>
						<strong><a href="http://sushigaming.com/">Sushigaming</a></strong><br>
						Awesome sponsors of Minotar.net!
					</p>
					<p>
						<a href="http://www.enjin.com/">Enjin</a><br>
						Guild Website Hosting.
					</p>
					<p>
						<a href="http://forums.bukkit.org/threads/econ-web-virtualshop-v2-3-fight-communism-with-free-market-1-shop-plugin-now-with-webui-1000.18948/">VirtualShop</a><br>
						Virtual Store plugin for Bukkit.
					</p>
					<p>
						<a href="http://minecraft-skins.com/">Minecraft Skins</a><br>
						Largest skin browsing site.
					</p>
					<p>
						<a href="http://yeahwh.at/">YEAHWH.AT?!</a><br>
						Large Minecraft Server
					</p>
					<p>
						<a href="http://massivecraft.com/">MassiveCraft</a><br>
						Massivecraft is a medieval fantasy role-playing Minecraft server.
					</p>
					<br>
					<p>Want to be added to the list? Email me at <a href="mailto:luke@axxim.net">luke@axxim.net</a></p><br>

					<h2>Plugins</h2><br>
					<p>
						<a href="http://ge.tt/3V2oBuF">IP.Board Plugin</a>
					</p>
					<p>
						<a href="http://wordpress.org/extend/plugins/minotar-minecraft-avatars/">WordPress Plugin</a>
					</p>
					<p>
						<a href="http://vanillaforums.org/addon/minecraftatar-plugin/">Vanilla Forum Plugin</a>
					</p>
				</div>
			</div>
		</div>

		<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.4.3/jquery.min.js"></script>
		<script type="text/javascript">
			$(function(){

				setInterval(update, 100);

				function update(){
					var incrementBy = 124;
					var curnum = parseInt($("#pageviews").html(),10)
						curnum = curnum + incrementBy;
					$("#pageviews").html(curnum);
				}

			});
		</script>
	</body>
</html>
