<!DOCTYPE html>
<html>
    <head>    
        <meta charset="utf-8" />
        
        <title>Minotar - The Miner's Avatar</title>
        <link href="https://fonts.googleapis.com/css?family=Cabin+Sketch:bold" rel="stylesheet" type="text/css">
		<link href='https://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
		
        <link rel="stylesheet" href="style.css" />
        <link rel="icon" type="image/png" href="https://minotar.net/avatar/clone1018/128.png" />      
        
        <!--[if IE]>
            <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>        
            <style type="text/css">
                .clear {
                  zoom: 1;
                  display: block;
                }
            </style>
        <![endif]-->

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>

        <script>
          var _gaq=[['_setAccount','UA-22574465-1'],['_trackPageview']];
          (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
          g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
          s.parentNode.insertBefore(g,s)}(document,'script'));
        </script>
    </head>
    
    <body>
    	
    	<section id="page">
    
            <header>
            
                <hgroup>
                    <h1><a href="/">Minotar</a></h1>
                    <h3>The Miner's Avatar</h3>
                </hgroup>
                                
                <nav class="clear"> <!-- The nav link semantically marks your main site navigation -->
                    <ul>
                        <li><a href="/">Home</a></li>
                        <li><a href="#api" title="Easy. Awesome. API.">API</a></li>
                        <li><a href="#plugins" title="Beautiful, wonderful plugins!">Plugins</a></li>
                        <li><a href="https://github.com/clone1018/Minotar" title="Bugs and Stuff!">GitHub</a></li>
                        <li><a href="https://twitter.com/#!/clone1018" title="Only because they wanted me to.">Twitter</a></li>
                    </ul>
                </nav>
            
            </header>
            
            <section id="articles"> <!-- A new section with the articles -->


				<!-- Article 1 start -->

                <div class="line"></div>  <!-- Dividing line -->
                <h2 style="text-align: center">Bandwidth Provided by <a href="http://vpsno.de">VPSNode</a></h2>
                <div class="line"></div>
                
                <article id="article1"> <!-- The new article tag. The id is supplied so it can be scrolled into view. -->
                    <h2>What's a Minotar?</h2>
                    
                    <div class="line"></div>
                    
                    <div class="articleBody clear">
                        <p>A Minotar is a global avatar that pulls the head off your Minecraft.net skin, and allows it for use anywhere that you can embed an image. See some uses below.</p>
                        <div style="text-align: center;">
                            <img src="//minotar.net/avatar/clone1018/64">
                            <img src="//minotar.net/avatar/citricsquid/64">
                            <img src="//minotar.net/avatar/Raitsui/64">
                            <img src="//minotar.net/avatar/runforthefinish/64">
                            <img src="//minotar.net/avatar/NoMercyJon/64">
                            <img src="//minotar.net/avatar/Nautika/64">
                            <img src="//minotar.net/avatar/Notch/64">
                            <img src="//minotar.net/helm/NiteAngel/64">
                            <img src="//minotar.net/helm/hyp3rdriv3/64">
                            <img src="//minotar.net/helm/S1NZ/64">
                            <img src="//minotar.net/helm/drupal/64">
                            <img src="//minotar.net/helm/wildhog101/64">
                            <img src="//minotar.net/helm/KakashiSuno/64">
                        </div><br>
                        <p style="text-align: center">Minotar Build:
                            <code>
                                <?php echo file_get_contents('./.git/refs/heads/master'); ?>
                            </code>
                        </p>
                    </div>
                </article>
                
				<!-- Article 1 end -->


				<!-- Article 2 start -->

                <div class="line"></div>
                <a name="api"></a>
                <article id="article2">
                    <h2>Sweet and Simple API</h2>
                    
                    <div class="line"></div>
                    
                    <div class="articleBody clear">
                        <h4>Simple Heads</h4>                        
                        <p>Unlike the PayPal API, we keep things nice and simple. For basic usage just provide a username:</p>
                        <pre><code>HTML5: &#60;img src="https://minotar.net/avatar/<span style="color: #1E90FF;">clone1018</span>"&#62;</code></pre><br>

                        <p>You can also set a size. We use pixels and we only need the <span style="color: #DC143C;">width</span>. Just add it to the end. </p>
                        <pre><code>HTML5: &#60;img src="https://minotar.net/avatar/<span style="color: #1E90FF;">clone1018</span>/<span style="color: #DC143C;">100</span>"&#62;</code></pre><br>

                        <p>And since some services require an extension we've added simple support for it. Just add <span style="color: #00FF00">.png</span> to the end. </p>
                        <pre><code>HTML5: &#60;img src="https://minotar.net/avatar/<span style="color: #1E90FF;">clone1018</span>/<span style="color: #DC143C;">100</span><span style="color: #00FF00">.png</span>"&#62;</code></pre><br>

                        <h4>Avatar With Helm</h4>
                        <p>Sometimes you want to display a helm too, that's fine with this endpoint:</p>
                        <pre><code>HTML5: &#60;img src="https://minotar.net/helm/<span style="color: #1E90FF;">clone1018</span>/<span style="color: #DC143C;">100</span><span style="color: #00FF00">.png</span>"&#62;</code></pre><br>

                        <br>
                        <p style="text-align: center;"><button id="showmore">Advanced API GET!</button></p>
                        <div id="moreapi" style="display: none">
                            <h4>User's Skin</h4>
                            <p>You can even use Minotar's API to get a users skin. <em>We're adding more soon!</em></p>
                            <pre><code>HTML5: &#60;img src="https://minotar.net/skin/<span style="color: #1E90FF;">clone1018</span>"&#62;</code></pre><br>
                            <p>You can also set the browser to download the image by using:</p>
                            <pre><code>HTTP: https://minotar.net/download/<span style="color: #1E90FF;">clone1018</span></code></pre><br>
                            <h4>Random Skin</h4>
                            <p>Randomly generated head? We got that too.</p>
                            <pre><code>HTML5: &#60;img src="https://minotar.net/random/<span style="color: #DC143C;">100</span><span style="color: #00FF00">.png</span>"&#62;</code>"&#62;</code></pre><br>
                        </div>
                    </div>
                </article>
                
				<!-- Article 2 end -->

				<!-- Article 3 start -->

                <div class="line"></div>
                <a name="plugins"></a>
                <article id="article3">
                    <h2>Plugins</h2>
                    
                    <div class="line"></div>
                    
                    <div class="articleBody clear">
                        <p><strong><a href="http://ge.tt/3V2oBuF">IP.Board Plugin</a></strong> - At the moment this plugin overwrites all avatar functions making them go to Minotar. The username is based on your Forum Display Name. </p>
                        <p><strong><a href="http://wordpress.org/extend/plugins/minotar-minecraft-avatars">WordPress Plugin</a></strong> - Fully supported avatar replacer. Based on the persons name field.</p>
                    </div>
                </article>

                <div class="line"></div>
                
                <article id="article3">
                    <h2>Who Uses Minotar?</h2>
                    
                    <div class="line"></div>
                    
                    <div class="articleBody clear">
                        <p>Tons of programs and websites use Minotar, here are some examples.</p>
                        <p><strong><a href="http://minecrafter.com">Minecrafter</a></strong> - Minecrafter is an all in one Minecraft hub for servers, mods, blocks, items, skins, maps and so much more.</p>
                        <p><strong><a href="http://mcserverlist.net">MCSL</a></strong> - MCServerlist is the worlds largest collection of multiplayer minecraft servers.</p>
                        <p><strong><a href="http://forums.bukkit.org/threads/misc-bananamaprender-1-6-generate-a-flatmap-image-render-of-your-world-1000.19775/">BananaMapRender</a></strong> - Flat Map Generator for Bukkit</p>
                        <p><strong><a href="http://forums.bukkit.org/threads/econ-web-virtualshop-v2-3-fight-communism-with-free-market-1-shop-plugin-now-with-webui-1000.18948/">VirtualShop</a></strong> - This plugin allows you to put items up for sale in a virtual store with a command and get paid via iConomy only when someone buys them.</p>
                        <p><strong><a href="http://minecraft-skins.com/">Minecraft Skins</a></strong> - A Skin Database packed with 350+ free &amp; unique Minecraft skins for you to choose from.</p>
                        <p><strong><a href="http://redstonepowered.com">RedstonePowered</a></strong> - The number one website for downloading Minecraft-mods and texture-packs.</p>
                        <p><strong><a href="http://massivecraft.com/">MassiveCraft</a></strong> - Massivecraft is a medieval fantasy roleplaying minecraft server.</strong>
                        <p>Want to be added? Email me luke@axxim.net</p>
                    </div>
                </article>


            </section>

        <footer> <!-- Marking the footer section -->
           <div class="line"></div>           
            <p>
                <a href="http://axxim.net">Copyright 2011 - Axxim, LLC</a>
            </p>

            <br><br>

            <p>
                This templated is a template, if you know where it came from <a href="mailto:luke@axxim.net">let me know</a> so I can give credit.
            </p>     
        </footer>

        </section> <!-- Closing the #page section -->

        <!-- Git Build: <?=file_get_contents('./.git/refs/heads/master')?>-->
        
        <script type="text/javascript">
            $("#showmore").click(function () {
              $("#moreapi").slideToggle("slow");
            });
        </script>

    </body>
</html>
